spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      max-size: 10
      max-idle-time: 1000

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${SPRING_AWS_ACCESS_KEY}
      secret-key: ${SPRING_AWS_SECRET_KEY}
    s3:
      bucket: resource.klock.app
      endpoint: https://resource.klock.app
      path-user-profile: user-profile
      path-user-trace-image: user-trace-image

crypto:
  key:
    store-password: ${SPRING_KEY_STORE_PASSWORD}
    alias: ${SPRING_KEY_ALIAS}
