spring:
  r2dbc:
    url: r2dbc:mysql://${app.common.db.host}:${app.common.db.port}?sslMode=DISABLED
    username: ${app.common.db.user}
    password: ${app.common.db.password}
    pool:
      max-size: 10
      max-idle-time: 1000
