# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klock-api-app-deployment
  namespace: klock
spec:
  selector:
    matchLabels:
      app: klock-api-app-pod
  template:
    metadata:
      labels:
        app: klock-api-app-pod
    spec:
      tolerations:
        - key: eks.amazonaws.com/compute-type
          operator: Equal
          value: ec2
          effect: NoSchedule
      containers:
        - name: klock-api-app-container
          image: $IMAGE_NAME
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/deploy/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/deploy/healthy
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: common,prod
            - name: SPRING_R2DBC_URL
              value: $DB_URL
            - name: SPRING_R2DBC_USERNAME
              value: $DB_USERNAME
            - name: SPRING_R2DBC_PASSWORD
              value: $DB_PASSWORD
            - name: SPRING_AWS_ACCESS_KEY
              value: $AWS_ACCESS_KEY
            - name: SPRING_AWS_SECRET_KEY
              value: $AWS_SECRET_KEY
            - name: SPRING_KEY_STORE_PASSWORD
              value: $KEY_STORE_PASSWORD
            - name: SPRING_KEY_STORE_ALIAS
              value: $KEY_ALIAS
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      nodeSelector:
        eks.amazonaws.com/compute-type: fargate
