# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: klock-api-app-service
  namespace: klock
spec:
  selector:
    app: klock-api-app-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
