apiVersion: v1
kind: Service
metadata:
  name: klock-api-app
spec:
  type: LoadBalancer
  selector:
    app: klock-api-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
